# -*- coding: utf-8 -*-
"""
Static "database" for the Museum of Minimalism demo site.
In a production app this would live in a real database (Postgres/SQLite);
here it's kept as plain Python structures to keep the demo self-contained.
"""

EXHIBITIONS = {
    "sequence": {
        "slug": "sequence",
        "title": "Sequence",
        "artist": "Richard Serra",
        "dates": "April 16, 2021 \u2022 June 16, 2021",
        "duration": "58:12",
        "image": "img/sequence.jpg",
        "ticket_image": "img/ticket-photo.jpg",
        "done_image": "img/done-photo.jpg",
        "artist_photo": "img/artist-portrait.jpg",
        "intro": (
            "One of the preeminent sculptors of our era, Richard Serra "
            "(American, b. 1938) has long been acclaimed for his challenging "
            "and innovative work, which emphasizes materiality and an "
            "engagement between the viewer, the site, and the work."
        ),
        "sections": [
            {
                "eyebrow": "minimal",
                "number": "01",
                "title": "Torqued Torus Inversion",
                "image": "img/concept-torus.jpg",
                "text": (
                    "In the early 1960s, Serra and the Minimalist artists of "
                    "his generation turned to unconventional, industrial "
                    "materials and began to accentuate the physical "
                    "properties of their art."
                ),
            },
            {
                "eyebrow": "concept",
                "number": "02",
                "title": "The Matter of Time",
                "image": "img/concept-time.jpg",
                "text": (
                    "Serra's sculpture is associated with a certain laconism "
                    "in form, as well as minimal plastic means aimed to reach "
                    "the maximum of expression."
                ),
            },
            {
                "eyebrow": "simple",
                "number": "03",
                "title": "Band",
                "image": "img/concept-band.jpg",
                "text": (
                    "His multi-tone self-supporting steel installations are "
                    "the result of a new sculptural mentality and reveal a "
                    "novel semantics in sculpture and in digital."
                ),
            },
        ],
        "artist_bio": (
            "Serra prefers that you look at his work as something that "
            "\u201cshapes space\u201d as you move through it, rather than "
            "something to be viewed as a stand-alone work. Travel through "
            "it, interact with it, stop, look around, turn around, walk "
            "back, look up, look down, stand with your back to one wall "
            "and then the other \u2013 basically change your position "
            "inside his space."
        ),
        "quote": (
            "I consider space to be a material. And I attempt to use "
            "sculptural form to make space distinct."
        ),
        "tickets": {
            "single": {"label": "Single ticket", "price": 15, "info": "1 ticket"},
            "tandem": {"label": "Tandem \u2022 2 tickets", "price": 26, "info": "2 tickets"},
            "combo": {"label": "Combo \u2022 3 tickets", "price": 36, "info": "3 tickets"},
        },
        "time_slots": [
            "10 am", "11 am", "12 pm", "1:30 pm", "2:30 pm", "3:30 pm",
            "4:30 pm", "6 pm", "7 pm", "8 pm", "9 pm", "10 pm",
        ],
        "interactions": {
            "360": {
                "label": "360\u00b0",
                "text": "Are immersive video recordings where a view in every direction is recorded simultaneously.",
                "requires": "computer or phone \u2022 headphones",
            },
            "xr": {
                "label": "XR",
                "text": "Extended reality is all real-and-virtual combined interactions generated by digital.",
                "requires": "computer \u2022 HTC Vive or Oculus Rift",
            },
            "guide": {
                "label": "Guide",
                "text": "Interactive online exhibition with a real guide and in 360 format.",
                "requires": "computer or phone \u2022 headphones",
            },
        },
    },
    "nominal": {
        "slug": "nominal",
        "title": "Nominal",
        "artist": "Dan Flavin",
        "dates": "April 23, 2021 \u2022 May 16, 2021",
        "duration": "32:10",
        "intro": "The exhibition examines Dan Flavin's use of different variations of fluorescent white light.",
        "image": "img/ex-nominal.jpg",
        "sections": [],
        "artist_bio": "",
        "quote": "",
        "tickets": {
            "single": {"label": "Single ticket", "price": 12, "info": "1 ticket"},
            "tandem": {"label": "Tandem \u2022 2 tickets", "price": 20, "info": "2 tickets"},
            "combo": {"label": "Combo \u2022 3 tickets", "price": 28, "info": "3 tickets"},
        },
        "time_slots": ["10 am", "11 am", "12 pm", "1:30 pm", "2:30 pm", "3:30 pm"],
        "interactions": {
            "360": {"label": "360\u00b0", "text": "Immersive video recordings.", "requires": "computer or phone \u2022 headphones"},
            "guide": {"label": "Guide", "text": "Interactive online exhibition with a real guide.", "requires": "computer or phone \u2022 headphones"},
        },
    },
    "perfection": {
        "slug": "perfection",
        "title": "Perfection",
        "artist": "Fashion",
        "dates": "May 25, 2021",
        "duration": "20:00",
        "intro": "Simplicity and conciseness, elegance and nobility, sophistication and tranquility - this is what we can say, characterizing the style of minimalism in fashion.",
        "image": "img/ex-perfection.jpg",
        "sections": [],
        "artist_bio": "",
        "quote": "",
        "tickets": {
            "single": {"label": "Single ticket", "price": 10, "info": "1 ticket"},
            "tandem": {"label": "Tandem \u2022 2 tickets", "price": 18, "info": "2 tickets"},
            "combo": {"label": "Combo \u2022 3 tickets", "price": 25, "info": "3 tickets"},
        },
        "time_slots": ["11 am", "1:30 pm", "3:30 pm", "6 pm"],
        "interactions": {
            "360": {"label": "360\u00b0", "text": "Immersive video recordings.", "requires": "computer or phone \u2022 headphones"},
        },
    },
    "conciseness": {
        "slug": "conciseness",
        "title": "Conciseness",
        "artist": "Jose Basso",
        "dates": "June 16, 2021 \u2022 July 22, 2021",
        "duration": "41:05",
        "intro": "Identification is only the central objects, the most important for correct perception.",
        "image": "img/ex-conciseness.jpg",
        "sections": [],
        "artist_bio": "",
        "quote": "",
        "tickets": {
            "single": {"label": "Single ticket", "price": 14, "info": "1 ticket"},
            "tandem": {"label": "Tandem \u2022 2 tickets", "price": 24, "info": "2 tickets"},
            "combo": {"label": "Combo \u2022 3 tickets", "price": 32, "info": "3 tickets"},
        },
        "time_slots": ["10 am", "12 pm", "2:30 pm", "6 pm", "8 pm"],
        "interactions": {
            "guide": {"label": "Guide", "text": "Interactive online exhibition with a real guide.", "requires": "computer or phone \u2022 headphones"},
        },
    },
}

RECOMMENDATIONS = [
    {"slug": "octahedron", "title": "Octahedron", "artist": "Tony Smith", "image": "img/recommend-octahedron.jpg"},
    {"slug": "chevrons", "title": "Chevrons", "artist": "Ronald Bladen", "image": "img/recommend-chevrons.jpg"},
]

EVENTS = [
    {
        "title": "Japanese Minimal Design",
        "type": "Lecture",
        "text": "Naoto Fukasawa creates minimalistic designs for the things that surround us. This lecture will explore simplicity, brevity, and Japanese craftsmanship.",
        "time": "1:30 pm",
        "date": "monday \u2022 May 17, 2021",
        "image": "img/event-japanese.jpg",
    },
    {
        "title": "Minimalism in our lives",
        "type": "Online cinema",
        "text": "Architects, designers, musicians, entrepreneurs and ordinary families share their experiences on how to live a more minimalistic and meaningful life.",
        "time": "3:30 pm",
        "date": "wednesday \u2022 May 19, 2021",
        "image": "img/event-minimalism.jpg",
    },
]

ARCHIVE = [
    {"title": "Base unit", "artist": "Sol LeWitt invented complex compositions composed of simple geometric shapes and colors.", "date": "April 15, 2021", "image": "img/archive-baseunit.jpg"},
    {"title": "Mirrored Cubes", "artist": "Robert Morris works a lot with mirrors, making his objects disappear, hide in the gallery space and make the viewer stand out.", "date": "April 15, 2021", "image": "img/archive-mirroredcubes.jpg"},
    {"title": "Spirit of the place", "artist": "Paul Stone demonstrates true minimalism in painting, depriving his work of a lot of detail.", "date": "April 15, 2021", "image": "img/archive-spirit.jpg"},
]

# Simple promo code table: code -> discount fraction
PROMO_CODES = {
    "MINIMAL10": 0.10,
    "SERRA20": 0.20,
}
